[phases.setup]
nixPkgs = ["chromium", "chromium-chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache/ms-playwright"
